### ISSUE TITLE
GetActivePositionsAsync returning NullReferenceException

### ISSUE THREAD

**Issue by baselkhateeb** [JKorf/Bitfinex.Net#12]
I traced down the error and it's coming from BaseConverter.ReadJson in CryptoExchange project.
Here's the stack trace:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CryptoExchange.Net
  StackTrace:
   ```
at CryptoExchange.Net.Converters.BaseConverter`1.<>c__DisplayClass5_0.<ReadJson>b__0(KeyValuePair`2 v) in \CryptoExchange.Net\Converters\BaseConverter.cs:line 28
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CryptoExchange.Net.Converters.BaseConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Users\Ahd-w10\source\repos\CryptoExchange.Net\Converters\BaseConverter.cs:line 32
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

```

**Comment by JKorf** [comment]
Hi, can you put LogVerbosity on Debug and share the data that was returned? There is an error parsing the returned data.

**Comment by baselkhateeb** [comment]
I found out that in BaseConverters.ReadJson() reader.Value was null and this line doesn't check for null before calling .ToString()
`var val = Mapping.SingleOrDefault(v => v.Value == reader.Value.ToString()).Key;`

I solved it by simply adding a null check like this:
`var val = Mapping.SingleOrDefault(v => v.Value == reader.Value?.ToString()).Key;`

I saw you solved this on CryptoExchange.net 4 hours ago.
Now it's working like a charm and retrieving the right positions.

**Comment by JKorf** [comment]
Ah okay. Yes I noticed there was no error/null checking on that bit so I added that after I saw where your error was coming from, but didn't know for sure if it would solve your problem. Glad it's fixed!
