### ISSUE TITLE
Unable to cast object of type JValue to type JArray

### ISSUE THREAD

**Issue by arkada38** [JKorf/Bitfinex.Net#136]
**Describe the bug**
I see a lot of exceptions in the Debug window.

**To Reproduce**
```csharp
using Bitfinex.Net;

BitfinexSocketClient client = new();

var res = await client.SubscribeToRawBookUpdatesAsync
(
	symbol: "tBTCUSD",
	limit: 1,
	handler: data => Console.WriteLine(data.Topic)
);

await Task.Delay(TimeSpan.FromSeconds(5));

Console.ReadKey();
```

**Expected behavior**
No exceptions

**Debug logging**
```
2021.10.06 18:41:06:139 | Error | Bitfinex   | Socket 1 Exception during message processing
Exception: InvalidCastException - Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.
   at Bitfinex.Net.BitfinexSocketClient.<>c__DisplayClass12_0.<SubscribeToRawBookUpdatesAsync>b__0(DataEvent`1 data)
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass74_0`1.<AddSubscription>g__InternalHandler|0(MessageEvent messageEvent)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: [
  164223,
  "cs",
  1081183392
]
```

**Comment by JKorf** [comment]
Fixed
