### ISSUE TITLE
Null reference exception on place order 

### ISSUE THREAD

**Issue by justinammerlaan** [JKorf/Bitfinex.Net#24]
Occasionally getting this exception on place order. Something to do with a dictionary you are using?

2018-06-06 14:56:25:743 | Debug | Received message: [87,"tu",[254599046,1528322020598,0.13307,605.58]]
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Bitfinex.Net.BitfinexSocketClient.<>c__DisplayClass62_0.<PlaceOrderAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Bitfinex.Net.BitfinexSocketClient.<PlaceOrderAsync>d__62.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
2018-06-06 14:56:25:772 | Debug | Received message: [0,"n",[1528322020814,"on-req",null,null,[13042123129,null,1152813656,"tETHUSD",null,null,0.2778,0.2778,"STOP",null,null,null,null,null,null,null,612.49,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null],null,"SUCCESS","Submitting stop buy order for 0.2778 ETH."]]
2018-06-06 14:56:25:772 | Debug | Received message: [0,"on",[13042123129,null,1152813656,"tETHUSD",1528322020794,1528322020816,0.2778,0.2778,"STOP",null,null,null,0,"ACTIVE",null,null,612.49,0,null,null,null,null,null,0,0,0,null,null,"API>BFX",null,null,null]]

**Comment by JKorf** [comment]
Can you see if this still happens on the latest release?

**Comment by JKorf** [comment]
I'll assume this is fixed. If not, please reopen the issue.
