### ISSUE TITLE
Error in processing loop. System.InvalidOperationException

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#28]
2018/06/21 13:58:18:286 | Error | Error in processing loop. System.InvalidOperationException, Sequence contains more than one matching element,    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: {"event":"subscribed","channel":"book","chanId":2246,"symbol":"tBCHBTC","prec":"P0","freq":"F0","len":"25","pair":"BCHBTC"}
13:58:18.28[32]DEBUG:[bitfinex] API: 2018/06/21 13:58:18:286 | Error | Error in processing loop. System.InvalidOperationException, Sequence contains more than one matching element,    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: {"event":"subscribed","channel":"book","chanId":2246,"symbol":"tBCHBTC","prec":"P0","freq":"F0","len":"25","pair":"BCHBTC"}

**Comment by JKorf** [comment]
Same issue as #26
