### ISSUE TITLE
Trades updates: errors in parsing ?

### ISSUE THREAD

**Issue by ciottied** [JKorf/Bitfinex.Net#31]
Hi.
VS Immediate windows posts errors in parsing trades:

```
2018/06/22 23.16.13.308 | Error | Error in processing loop. Newtonsoft.Json.JsonSerializationException, Error converting value "EXCHANGE LIMIT" to type 'System.Nullable`1[Bitfinex.Net.Objects.OrderType]'. Path '[6]', line 1, position 81.,    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at CryptoExchange.Net.Converters.ArrayConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Bitfinex.Net.Objects.SocketObjects.SubscriptionRegistration.Handle(JArray obj)
   at Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: [0,"te",[260754156,"tBTCUSD",1529702173281,13583268783,-0.5,5968,"EXCHANGE LIMIT",5968,1]]

2018/06/22 23.16.13.332 | Error | Error in processing loop. Newtonsoft.Json.JsonSerializationException, Error converting value "EXCHANGE LIMIT" to type 'System.Nullable`1[Bitfinex.Net.Objects.OrderType]'. Path '[6]', line 1, position 81.,    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at CryptoExchange.Net.Converters.ArrayConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Bitfinex.Net.Objects.SocketObjects.SubscriptionRegistration.Handle(JArray obj)
   at Bitfinex.Net.BitfinexSocketClient.ProcessData(), message: [0,"tu",[260754156,"tBTCUSD",1529702173281,13583268783,-0.5,5968,"EXCHANGE LIMIT",5968,1,-2.984,"USD"]]

```

**Comment by JKorf** [comment]
Hi I found the issue and this should be fixed in the latest version.

**Comment by ciottied** [comment]
thanks.
