### ISSUE TITLE
UnobservedTaskException when placing order

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#35]
2018/06/28 18:18:12:993 | Debug | Creating request for https://api.bitfinex.com/v1/order/new
18:18:12.99[88]DEBUG:[bitfinex] API: 2018/06/28 18:18:12:993 | Debug | Creating request for https://api.bitfinex.com/v1/order/new
2018/06/28 18:18:13:002 | Debug | Sending signed request to https://api.bitfinex.com/v1/order/new with parameters symbol=btcusd, amount=0.001, price=6113, exchange=bitfinex, side=sell, type=exchange limit, 
18:18:13.00[88]DEBUG:[bitfinex] API: 2018/06/28 18:18:13:002 | Debug | Sending signed request to https://api.bitfinex.com/v1/order/new with parameters symbol=btcusd, amount=0.001, price=6113, exchange=bitfinex, side=sell, type=exchange limit, 
18:18:13.16[2]FATAL:UnobservedTaskExceptio: 
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Bitfinex.Net.BitfinexSocketClient.<SubscribeAndWait>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Bitfinex.Net.BitfinexSocketClient.<SubscribeUnsend>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Bitfinex.Net.BitfinexSocketClient.<<SocketOpened>b__91_0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Bitfinex.Net.BitfinexSocketClient.<SubscribeAndWait>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Bitfinex.Net.BitfinexSocketClient.<SubscribeUnsend>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Bitfinex.Net.BitfinexSocketClient.<<SocketOpened>b__91_0>d.MoveNext()<---

2018/06/28 18:18:13:214 | Warning | Server returned an error: {"message":"Invalid order: minimum size for BTC/USD is 0.002"}
18:18:13.21[43]DEBUG:[bitfinex] API: 2018/06/28 18:18:13:214 | Warning | Server returned an error: {"message":"Invalid order: minimum size for BTC/USD is 0.002"}

**Comment by JKorf** [comment]
Can you see if you still get this in the latest version? Should be fixed.

**Comment by JKorf** [comment]
Assuming this is fixed, if not please reopen.
