### ISSUE TITLE
Start after SocketClient is stopped throws NullReferenceException

### ISSUE THREAD

**Issue by henningms** [JKorf/Bitfinex.Net#38]
Not sure if it's meant to be done this way, but I stop the socketClient whe my apps go to sleep and then try to start the client again when it resumes.

When trying to cal Start() again after stopped I get:

```
   System.NullReferenceException
   at CryptoExchange.Net.Implementation.BaseSocket.get_IsClosed()
   at Bitfinex.Net.BitfinexSocketClient.CheckConnection()
   at Bitfinex.Net.BitfinexSocketClient.StartInternal()
   at Bitfinex.Net.BitfinexSocketClient.Start()
-----
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by JKorf** [comment]
Small bug, fixed in the latest version. Thanks for the report.
