### ISSUE TITLE
BitfinexSocketClient is not thread-safe

### ISSUE THREAD

**Issue by xjohnwu** [JKorf/Bitfinex.Net#67]
Firstly, please check the error below:

> [Debug] 2018/12/12 15:03:05:674 | Error | Socket 2 Exception during message processing
> Processor: DataHandler
> Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CryptoExchange.Net.Sockets.SocketSubscription.GetWaitingEvent(String name)
   at Bitfinex.Net.BitfinexSocketClient.DataHandlerQuery(BitfinexSocketSubscription subscription, JToken data, Action`1 handler)
   at Bitfinex.Net.BitfinexSocketClient.<>c__DisplayClass50_0`1.<Query>b__2(SocketSubscription subs, JToken data)
   at CryptoExchange.Net.SocketClient.ProcessMessage(SocketSubscription subscription, String data)

After looking into the code closely, I realise that Query<T>() method always call

var waitTask = subscription.WaitForEvent(DataEvent, request.Id, socketResponseTimeout);

However, if you call PlaceOrder and CancelOrder at the same time, both calls will stop and wait for the "Data" event, hence resulting in the above error.

I would suggest giving the wait event a more unique name, e.g. include the request id as part of the name. This will make the SocketClient more thread-safe.

Meanwhile my workaround is to synchronise all methods that call Query<T>(), in particular PlaceOrderAsync() and CancelOrderAsync()

Hope this helps :)

(The reason why I don't just fix the bug and create a merge request is because the fix involves changing the base class SocketClient, which lives in the CryptoExchange.Net project...)

Thanks a lot!

**Comment by xjohnwu** [comment]
Adding synchronization doesn't help. However, the good news is that I finally realise what's wrong :)
The reason for this error is because I try to cancel an order that is already cancelled. Hence, the wait for the cancelled order event times out. However, after it times out it doesn't remove itself from the event queue, hence the following PlaceOrder or CancelOrder calls will add another of the same event to waitingForEvents list, resulting in the above error.

A simple fix is to use HashSet<SocketEvent> instead of List<SocketEvent>.
