### ISSUE TITLE
Bitfinex fatal exception

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#69]
22:32:24.13[69048]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:136 | Info | Socket 39 reconnected after 00:00:05.4029409
22:32:24.27[85647]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:273 | Info | Socket 39 Connection lost, will try to reconnect
22:32:24.38[79584]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:382 | Info | Socket 2 reconnected after 00:00:05.3999422
22:32:24.52[85655]DEBUG:[Bitfinex] API: 2018/12/20 22:32:24:521 | Info | Socket 2 Connection lost, will try to reconnect
22:32:29.74[80069]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:743 | Info | Socket 39 reconnected after 00:00:05.4689161
22:32:29.87[80068]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:874 | Info | Socket 2 reconnected after 00:00:05.3519608
22:32:29.89[84937]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:893 | Info | Socket 39 Connection lost, will try to reconnect
22:32:29.99[84937]DEBUG:[Bitfinex] API: 2018/12/20 22:32:29:995 | Info | Socket 2 Connection lost, will try to reconnect
22:32:35.38[69048]DEBUG:[Bitfinex] API: 2018/12/20 22:32:35:386 | Info | Socket 39 reconnected after 00:00:05.4919072
22:32:35.38[11093]DEBUG:[Bitfinex] API: 2018/12/20 22:32:35:386 | Info | Socket 2 reconnected after 00:00:05.3909459
22:32:35.60[85831]FATAL:UnhandledException: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at CryptoExchange.Net.Sockets.SocketSubscription.ResetEvents()
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass20_0.<CreateSocket>b__0()
   at CryptoExchange.Net.Sockets.BaseSocket.Handle(List`1 handlers)
   at CryptoExchange.Net.Sockets.BaseSocket.<Connect>b__75_2(Object o, EventArgs s)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at SuperSocket.ClientEngine.ClientSession.OnClosed()
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.Close()
   at WebSocket4Net.Command.Close.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
22:32:35.60[1]DEBUG:OnAppExited

**Comment by JKorf** [comment]
I assume this one is no longer relevant due to new versions. If you still have this issue please let me know
